### ISSUE TITLE
Setattr on parameters can fail when making a copy

### ISSUE THREAD

**Issue by philippjfr** [holoviz/param#265]
In certain cases param makes copies of parameters which uses the internal ``__setstate__`` and ``__setattr__`` methods. Recent changes to ``Parameter.__setattr__`` which allow the ``watch`` mechanism to work can cause issues when copying parameters in this way because the code attempts to find the ``old`` value of the Parameter which does not exist before ``__setstate__`` has completed leading to this traceback:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-6e122cef8e3b> in <module>()
----> 1 Example.unbounded_float = 3.14

~/topographica/external/param/param/parameterized.py in __setattr__(mcs, attribute_name, value)
   1393         if parameter and not isinstance(value,Parameter):
   1394             if owning_class != mcs:
-> 1395                 type.__setattr__(mcs,attribute_name,copy.copy(parameter))
   1396             mcs.__dict__[attribute_name].__set__(None,value)
   1397 

~/miniconda/envs/anacondaviz/lib/python3.6/copy.py in copy(x)
    104     if isinstance(rv, str):
    105         return x
--> 106     return _reconstruct(x, None, *rv)
    107 
    108 

~/miniconda/envs/anacondaviz/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
--> 282             y.__setstate__(state)
    283         else:
    284             if isinstance(state, tuple) and len(state) == 2:

~/topographica/external/param/param/parameterized.py in __setstate__(self, state)
    619         # set values of __slots__ (instead of in non-existent __dict__)
    620         for (k,v) in state.items():
--> 621             setattr(self,k,v)
    622 
    623 

~/topographica/external/param/param/parameterized.py in __setattr__(self, name, value)
    503             old = getattr(self,name) if implemented else NotImplemented
    504         except AttributeError as e:
--> 505             raise e
    506             if name in self.__slots__:
    507                 old = NotImplemented

~/topographica/external/param/param/parameterized.py in __setattr__(self, name, value)
    501         implemented = (name!="default" and hasattr(self,'subscribers') and name in self.subscribers)
    502         try:
--> 503             old = getattr(self,name) if implemented else NotImplemented
    504         except AttributeError as e:
    505             raise e

AttributeError: bounds
```

**Comment by philippjfr** [comment]
Here is a minimal reproducible example:

```python
import param

class A(param.Parameterized):
    
    a = param.Number(default=0)
    
class B(A):
    
    pass

B.param.watch(lambda x: x, 'a', 'bounds')

B.a = 3.14
```

**Comment by ceball** [comment]
No doubt you've found an issue, but is there maybe a typo or copy/paste error in your example?

```
$ python issue265.py
$ cat issue265.py
import param

class A(param.Parameterized):

    a = param.Number(default=0)

class B(A):

    pass

B.param.watch(lambda x: x, 'a', 'bounds')

B.a = 3.14
$ git log -1
commit 56764fd599c86704ea9dd6636586e284744688fa
Author: Philipp Rudiger <philippjfr@continuum.io>
Date:   Tue Sep 18 17:01:05 2018 +0100

    Param depends improvements (mainly for depending on all parameters of a subobject; #264)
[...]

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        issue265.py

nothing added to commit but untracked files present (use "git add" to track)
```

Or have I missed something?

**Comment by philippjfr** [comment]
Pretty confused now, exact same setup:

```
(anacondaviz) 0276-prudiger:param philippjfr$ cat issue265.py
import param

class A(param.Parameterized):

    a = param.Number(default=0)

class B(A):

    pass

B.param.watch(lambda x: x, 'a', 'bounds')

B.a = 3.14
(anacondaviz) 0276-prudiger:param philippjfr$ python issue265.py
Traceback (most recent call last):
  File "issue265.py", line 13, in <module>
    B.a = 3.14
  File "/Users/philippjfr/topographica/external/param/param/parameterized.py", line 1387, in __setattr__
    type.__setattr__(mcs,attribute_name,copy.copy(parameter))
  File "/Users/philippjfr/miniconda/envs/anacondaviz/lib/python3.6/copy.py", line 106, in copy
    return _reconstruct(x, None, *rv)
  File "/Users/philippjfr/miniconda/envs/anacondaviz/lib/python3.6/copy.py", line 282, in _reconstruct
    y.__setstate__(state)
  File "/Users/philippjfr/topographica/external/param/param/parameterized.py", line 613, in __setstate__
    setattr(self,k,v)
  File "/Users/philippjfr/topographica/external/param/param/parameterized.py", line 501, in __setattr__
    old = getattr(self,name) if (name!="default" and hasattr(self,'subscribers') and name in self.subscribers) else NotImplemented
AttributeError: bounds
(anacondaviz) 0276-prudiger:param philippjfr$ git log -1
commit 56764fd599c86704ea9dd6636586e284744688fa
Author: Philipp Rudiger <philippjfr@continuum.io>
Date:   Tue Sep 18 17:01:05 2018 +0100

    Param depends improvements (mainly for depending on all parameters of a subobject; #264)

    Refactor of param depends, adding support for listening to all subobject parameters with subobject.param spec.
```

**Comment by philippjfr** [comment]
Maybe a Python version difference, I've got 3.6.4.

**Comment by tonyfast** [comment]
Can't reproduce this in 3.7 . Please reopen if this is still a problem for anyone.

**Comment by ovidner** [comment]
I can reproduce this error when adapting the example to use an `Integer` instead of a `Number`, like so:
```python
import param

class A(param.Parameterized):
    
    a = param.Integer(default=0)
    
class B(A):
    
    pass

B.param.watch(lambda x: x, 'a', 'bounds')

B.a = 3
```

I have also proposed a solution in #675.
