### ISSUE TITLE
ObjectSelector does not reset to None if objects are empty

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/param#399]
#### My Pain

I'm trying to create an app where the objects of an ObjectSelector updates dynamically. 

For example if you have Region and Country ObjectSelectors you would like the objects of the Country ObjectSelector to change when the value of the Region ObjectSelector change.

But sometimes the objects of the ObjectSelector might be the empty dictionary or list. This is not handled well.

The value is not automatically changed to None and it cannot be done programmatically. Instead the old value which is no longer in the list is kept.

I would expect the value to be set to None. Because otherwise if would have to check the objects before I running some function based on the change. Thats not natural I believe.

```bash
$ python 'issue_object_selector.py'
1
Traceback (most recent call last):
  File "issue_object_selector.py", line 20, in <module>
    app.value=None
  File "C:\Users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\param\parameterized.py", line 294, in _f
    instance_param.__set__(obj, val)
  File "C:\Users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\param\parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "C:\Users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\param\parameterized.py", line 823, in __set__
    self._validate(val)
  File "C:\Users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\param\__init__.py", line 1242, in _validate
    "valid options include %s"%(val,attrib_name, items))
ValueError: None not in Parameter value's list of possible objects, valid options include []
(.venv)
```

```python
import param
OBJECTS_ALL = {"First":1, "Second": 2}


class App(param.Parameterized):
    value = param.ObjectSelector(default=1, objects=OBJECTS_ALL)

    @param.depends("value", watch=True)
    def update(self):
        print(self.param.value.objects)
        print(self.value)

app = App()
object_dict = {}
objects = list(object_dict.values())
app.param.names = object_dict
app.param.value.objects = objects
assert app.value==1
print(app.value)
app.value=None
```

**Comment by MarcSkovMadsen** [comment]
I can then just set `allow_None` to be allowed to set it. Unfortunately it does not change automatically.

```bash
$ python 'issue_object_selector.py'
1
[]
None
(.venv)
```

```python
import param
OBJECTS_ALL = {"First":1, "Second": 2}


class App(param.Parameterized):
    value = param.ObjectSelector(default=1, objects=OBJECTS_ALL, allow_None=True)

    @param.depends("value", watch=True)
    def update(self):
        print(self.param.value.objects)
        print(self.value)

app = App()
object_dict = {}
objects = list(object_dict.values())
app.param.names = object_dict
app.param.value.objects = objects
assert app.value==1
print(app.value)
app.value=None
```

**Comment by ceball** [comment]
@MarcSkovMadsen when you create a new issue, do you get this prompt?

![iss](https://user-images.githubusercontent.com/1929/79322845-4e184980-7f05-11ea-80dd-b8946449fe7d.png)

If not, what do you get? (And what are you clicking on to create a new issue?

I'm trying to understand why new issues come in without the default holoviz template stuff (i.e. default sections and labels)...

**Comment by MarcSkovMadsen** [comment]
Yes. I get that prompt. I then clicked "Get started" under bug report.

**Comment by ceball** [comment]
When I do that, I get this:

![Screenshot from 2020-04-16 21-08-00](https://user-images.githubusercontent.com/1929/79501691-616f0600-8026-11ea-9dba-837ccd39239b.png)

I.e. my issue will be opened with some default labels. But that doesn't happen for you? (And therefore I guess it won't happen for others? Hmm. I wonder what I have done wrong...?)

**Comment by kcpevey** [comment]
Coming back to the issue being reported.

This is related to #412 . It looks like there is no mechanism in place to update the default value when the list of objects gets updated.

**Comment by jbednar** [comment]
Coming back to the original issue being reported here, I think it's the same type of problem as #412, i.e. that there has never been any mechanism in place to update the ObjectSelector's value when the list of allowed objects changes. As for #412, when ObjectSelector was written there was no watching mechanism available, but as in that case, now that we have it, we should presumably put in such a callback.  What we need to watch isn't a Parameter, though, so it's tricky.  I think this is a reasonable request, but don't quite know how to satisfy it with the current architecture.

**Comment by jbednar** [comment]
(And in the meantime it is the user's responsibility to update the default value if they change the list of objects, which is not ideal but was always how it was designed.)

**Comment by jbednar** [comment]
I'd still like to see an implementation for the behavior requested here, but I guess if it's the last thing needed before 2.0 and we don't have it, then we should punt this item to the wishlist. I agree that what @MarcSkovMadsen  suggests is the right behavior.

**Comment by maximlt** [comment]
I started to have a look at this issue and wish we could implement it, however, there's a lot of moving pieces and it's a pretty big change, I doubt we'll have the time to get it in, it might well be a Param 3.0 feature:

- We have not really decided whether `ObjectSelector` should concretely been deprecated and removed. It seems like the plan was to deprecate it (e.g. https://github.com/holoviz/param/issues/493), and it's effectively marked as deprecated in its docstring (https://github.com/holoviz/param/issues/728), yet `ObjectSelector` is still widely used. I found about 150 occurrences in the HoloViz source codes, ignoring those found in docs and in Param.
- It seems to me that this feature request would only address a subset of the more general problem of handling updates of `objects` As a user, I'd probably be surprised to see that the value of a Selector is only automatically updated when `objects` is set to an empty list/dict. By default, I guess we could select the first element in the dict/list, it'd be nice to have an API to simultaneously update the objects and set the value when you don't want the first one, to trigger only one event.
- While `allow_None` makes sense for Parameters like `String` or `Number, it muddies the water with Selectors (https://github.com/holoviz/param/issues/695#issuecomment-1546237556) as users can instead add `None` in the objects (`[None, ...]` or {"": None, ...}`). `allow_None`/`None` is also handled quite differently for Selector compared to other Parameters (this is from Param 1.13.0, I need to make sure all of that has been preserved with the sentinel PR):

```python
import param

class P(param.Parameterized):
    o1 = param.ObjectSelector(objects=[1, 2])
    s1 = param.Selector(default=None, objects=[1, 2])

assert P.o1 is None
# !! Normally when default is `None` allow_None is automatically set to `True`
# this is a very old change from 2015:
# https://github.com/holoviz/param/commit/a2ac1c9d83593aa64c930beddf5f1cffa1eb8744
assert P.param.o1.allow_None is not True  

# !! I've asked for default to be `None` but the autodefault took over
assert P.s1 == 1
```
- The current default value of `allow_None` for Selectors is `None` (https://github.com/holoviz/param/commit/bdfa2a9cb304459cfc4603905f10b6db7e992ce8#diff-b4344305e71345c3583ee7c047c524b6b272f31f6af55e2b14c54914b1476cd1R938), unlike the other Parameters that have `allow_None=False` by default. We recently discussed that in https://github.com/holoviz/param/issues/695. The lines are quite blurred there, but `allow_None=None` being falsy, one could ask whether setting the parameter value to `None` after `objects` is updated to an empty list/dict, as asked in this issue, should raise an error if `allow_None` is not `True`?
- If `check_on_set` is `True` and `objects` is emptied and the Parameter value set to `None`, should `None` be added to `objects`? I presume not.
- Overall, `allow_None` may just be a bad fit for Selectors, which instead may need an attribute to declare whether it's possible or not to _deselect_ the selected value, in which case the value would not be set to `None` but to some other sentinel value, to circumvent the pitfall of `None` being used as a sentinel value in context where it could be a valid option? Having the possibility to have an empty option in a Select widget is a [common pattern](https://stackoverflow.com/questions/8605516/set-the-select-option-as-blank-as-default-in-html-select-element). One might actually think you'd get that in Panel by using an `ObjectSelector` as its default value in `None`, almost actually, it's just that the displayed *Select* widget doesn't show that the value is `None` (and there's no way to go back to the deselected case after selecting an option):
![image](https://github.com/holoviz/param/assets/35924738/41a30c64-97a1-4715-96ac-29aa8e30661c)
![image](https://github.com/holoviz/param/assets/35924738/f0ea9762-e279-44cf-a03e-db1711fa788b)

So yes, there's very little chance this happens before Param 2.0 I think! I'd say a way forward could be to design what a better selector Parameter would like like in Param, after all the years of experience accumulated with Selector/ObjectSelector and their integrations in Panel, and see whether there's a path forward with the current implementation.
