### ISSUE TITLE
parameters good, parameterized bad / "gradual" param

### ISSUE THREAD

**Issue by ceball** [holoviz/param#435]
Param looks like an interesting library, but unfortunately I can never use it because by the time I ever get to a codebase, it's too late! People already wrote their classes and stuff, and it's not possible to make them inherit from parameterized.

I've proposed variants of "gradual parameterization" in the past. One day I'll try to write a decent overall proposal here in this issue. However, looking at param's code today I saw a comment:

https://github.com/holoviz/param/blob/b785c42e8745644ad74aa0ace758925f311443e1/param/parameterized.py#L2190-L2191

Usually my reminder comments fade into obscurity 30 mins after being written, but that one is actually useful. Following it (see the associated PR) , I can immediately get:

```python
import param

class A:
    a0 = param.Number(default=0,doc="a0 doc")
```

```
>>> a = A()
>>> a.a0 = "number"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sefkw/proj/param-gradual/param/param/parameterized.py", line 303, in _f
    return f(self, obj, val)
  File "/home/sefkw/proj/param-gradual/param/param/__init__.py", line 623, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/home/sefkw/proj/param-gradual/param/param/parameterized.py", line 303, in _f
    return f(self, obj, val)
  File "/home/sefkw/proj/param-gradual/param/param/parameterized.py", line 873, in __set__
    self._validate(val)
  File "/home/sefkw/proj/param-gradual/param/param/__init__.py", line 882, in _validate
    raise ValueError("Parameter '%s' only takes numeric values"%(self.name))
ValueError: Parameter 'a0' only takes numeric values
```

Of course, Parameterized and ParameterizedMeta class do a bunch of other stuff. However, I feel like it should be possible to factor that stuff out of those and also make it available another way. E.g. via a decorator people can use on their class. Or a number of decorators, each of which adds some particular functionality, if it makes sense on its own.

**Comment by jbednar** [comment]
Very interesting!  You still have to edit the source code of `A`, but here `A` could be inheriting from some class that you _can't_ modify.  I'm in favor of making the power of Param available in cases where the full approach can't be adopted but we can still provide some benefit.

**Comment by ceball** [comment]
Right, the fundamental thing is getting benefits of parts of param without having to go all in.
There are multiple themes/use cases that an issue called "gradual param" might be addressing. I'll brain dump some below - but because I am probably motivated here by wanting to do some "fun" programming for a change, I'm more likely just to play around and see what comes out than attempt to justify anything in a proposal that makes sense :)

(I think panel is likely to be generally the most motivating use case for param, so I'll probably talk about panel below, but of course we might like other benefits of param to spread too.)


### 1. You are class/function author, but don't want all of param

You are writing a class but you can't or don't have confidence/inclination to (yet) inherit from someone else's base class (`param.Parameterized`), but you'd like some benefit(s) from param.

You can add `param.Parameter`s for just some specific attributes. And you can decorate your class to get more aspects of param.

This is likely to be the use case my PR will address.

### 2. You have a class or instance that you can't modify

Maybe you want to use e.g. panel in a "Parameterized classes API"-like way (https://panel.holoviz.org/user_guide/APIs.html) on some existing classes/functions, but you can't modify them. Or you have an existing instance, and can't modify it (other than normal interaction, e.g. changing some attribute's value).

You can transform/adapt a class, e.g. inheriting from the class you can't modify. Or you can transform/adapt an existing object, getting a new one. The result is then suitable for use in panel without further thought. I say panel, but it could be some other use of param. E.g. you want a stricter version of something. 

(In the instance/object case, this could be as a "proxy" or not, e.g. after you safely set an attribute on your parameterized version, e.g. in panel gui, the change could be reflected back to the original or not.)

### 3. You can _add_ new things to existing class/function/object, but can't _modify_ anything that already exists

Maybe you want to use panel as above on an existing code base, but you can't _modify_ anything already existing, e.g. the class hierarchy, or existing attributes - but you can _add_ new things.

You might add information ("hints"/"annotations"...) to a class. E.g. for a class with attribute `thing`, you could add a hint like `thing` is `param.Number(doc="blah", bounds=(1, None))`. Those can be used e.g. by panel, because param would know how to convert (using the hints).

And if `.param` had been added (e.g. via decorating a class or adding to an object), the information could also be used for e.g. `your_object.param.set()` (or is it `.set_param()` - whatever).

The difference between this case and 2 above is that here you are able to store "domain knowledge" in the original source/class, so all users of the class can make use of it - it makes sense to store the information with the class rather than scattered elsewhere as in 2. This case differs from 1 because here you can't change an existing attribute into a parameter.

### general notes

In cases 2 and 3 above, we'd need to consider what happens if e.g. a value is set on the original thing outside the bounds allowed by parameters. Maybe constraints can be relaxed or ignored in that case. (E.g. imagine panel expecting a number with some bounds and planning to use a slider, but encountering a number outside the bounds, so increasing the bounds, or maybe encountering a string and so just using a text input widget instead.)

Even in case 1, it's interesting to think about the same question. With an attribute being a parameter, it couldn't be set outside the bounds or whatever - it would be an error. However, in a large existing codebase, you might turn a pre-existing attribute into a parameter, and specify some bounds or whatever, but still want to allow code to continue to run without failing (at least for a period) - so maybe you could start logging/warning to start with, maybe even recording how bad things get so you learn the current typical bounds.

### other "gradual param" ideas

* param is not supposed to incur much performance penalty on getting (whereas there is a penalty on setting that depends on the checking). However, there is no doubt some performance penalty on getting. (Why that is a concern to people using python in the first place, I just don't know ;) ) To allay fears about that, could also offer a way to have a parameter only be a parameter until it's first set on an instance, at which point it just becomes a normal attribute. However, this loses a lot of the benefits/interesting features of param. Also the more "broken up" or "optional" bits there are, the more confusing everything becomes (let alone having to document it...).

* (I'm sure there are more...e.g. for people coming with dataclasses and type annotations, but that's definitely a separate issue...)
