### ISSUE TITLE
Parameter ObjectSelector misses changes in subobjects

### ISSUE THREAD

**Issue by mdk73** [holoviz/param#462]
I want to use a set of instances (eg. A1 and A2) of a parameterized class A in a second parameterized class B. 
Via @param.depends B shall act on parameter changes (event or aparameter change) in A1 or A2.

For this purpose I create 
* a list containing the instances A1 and A2
* and use an ObjectSelector in class B to choose between the instances A1 and A2.

I would expect that the event set in the choosen instance of A1 or A2 would trigger the callback of B.
What I get is, that B with choosen A1 works, but with choosen A2 does not work.

```python
import panel as pn
import param

class A(param.Parameterized):
    event = param.Event()

    @param.depends('event', watch=True)
    def on_event(self):
        print('{}: on event'.format(self.name))

a_list = [
    A(name='A1'), 
    A(name='A2')]

class B(param.Parameterized):

    a = param.ObjectSelector(
        default=a_list[0],
        objects=a_list)
    
    @param.depends('a.event', watch=True)
    def on_a_event(self):
        print('{}: on a.event'.format(self.name))

    @param.depends('a', watch=True)
    def on_a(self):
        print('{}: a changed to: {}'.format(self.name, self.a))

if __name__ == '__main__':
    pn.extension()
    print('panel version: {}'.format(pn.__version__))
    print('param version: {}'.format(param.__version__))

    b = B(name='B')

    controlgui = pn.Column(b.param)
    server = controlgui.show(threaded=False)
```
![image](https://user-images.githubusercontent.com/2737768/110306222-df048180-7ffd-11eb-9a52-3a1a9afdf805.png)
![image](https://user-images.githubusercontent.com/2737768/110306172-ceeca200-7ffd-11eb-8d52-7649a0d58c0e.png)

Console output:
```
panel version: 0.10.3
param version: 1.10.1
Launching server at http://localhost:50976
WARNING:tornado.access:404 GET /favicon.ico (::1) 0.00ms
A1: on event
B: on a.event
B: a changed to: <A A2>
A2: on event
```

**Comment by jlstevens** [comment]
Actually I noticed some errors in my terminal so things may not be working quite right after all, even with my versions:

```
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fd08b786110>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/bokeh/server/session.py:51> exception=ValueError("'value' is not a parameter of Row00018")>)
Traceback (most recent call last):
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/bokeh/server/session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/tornado/gen.py", line 191, in wrapper
    result = func(*args, **kwargs)
  File "/Users/jstevens/Desktop/development/panel/panel/reactive.py", line 252, in _change_coroutine
    self._change_event(doc)
  File "/Users/jstevens/Desktop/development/panel/panel/reactive.py", line 262, in _change_event
    self._process_events(events)
  File "/Users/jstevens/Desktop/development/panel/panel/reactive.py", line 245, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/param/parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/param/parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/param/parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/jstevens/Desktop/development/panel/panel/param.py", line 409, in link_widget
    self.object.param.set_param(**{p_name: change.new})
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/param/parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/param/parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/param/parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/jstevens/Desktop/development/panel/panel/param.py", line 483, in link
    widget.param.set_param(**updates)
  File "/Users/jstevens/miniconda3/envs/analytics/lib/python3.7/site-packages/param/parameterized.py", line 1463, in set_param
    raise ValueError("'%s' is not a parameter of %s" % (k, self_or_cls.name))
ValueError: 'value' is not a parameter of Row00018
```

I'll need to think a bit about what this really means...

**Comment by mdk73** [comment]
Hi @jlstevens,

thanks for looking into the issue.

Unfortunately your output does not show, that the issue is solved by the new version of panel.

When `A1.event` is triggered, the output is `A1: on event`. And similar for `A2`.
This is working.

The crucial part is, wether `B` is recognizing that event or not.
It works if `A1` is selected for variable `B.a` , the output looks like this:

```
A1: on event
B: on a.event
```

It does not work if `A2` is selected for variable `B.a` , the output looks like this:
```
A2: on event
```
The line `B: on a.event` is missing, so `B` seems not to recognize the triggered event `A2.event`.

**Comment by maximlt** [comment]
I cannot reproduce based on the latest Panel and Param on the *main* branch. The last line below is the difference with what the OP shared.

```
A1: on event
B: on a.event
B: a changed to: <A A2>
A2: on event
B: on a.event
```
